package vista;


import java.util.List;
import modelo.Administrador;
import modelo.Usuario;
import utils.AccionesEnum;

public class BienvenidoUsuario extends javax.swing.JFrame {

    private Usuario usuario;
    
    public BienvenidoUsuario(Usuario usuario) {
        this.usuario = usuario;
        setLocationRelativeTo(null);
        initComponents();
        
        if(usuario instanceof Administrador){
            jMenuCesta.setVisible(false);
            jMenuItemNuevaCesta.setVisible(false);
            jMenuItemListarCesta.setVisible(false);
        }else{
            jMenuCesta.setVisible(false);
            jMenuItemAlta.setVisible(false);
            jMenuItemListar.setVisible(false);
            jMenuProducto.setVisible(false);
            jMenuItemAltaProducto.setVisible(false);
            jMenuItemListarProdcuto.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenido = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jButtonLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuCliente = new javax.swing.JMenu();
        jMenuItemAlta = new javax.swing.JMenuItem();
        jMenuItemListar = new javax.swing.JMenuItem();
        jMenuProducto = new javax.swing.JMenu();
        jMenuItemAltaProducto = new javax.swing.JMenuItem();
        jMenuItemListarProdcuto = new javax.swing.JMenuItem();
        jMenuCesta = new javax.swing.JMenu();
        jMenuItemNuevaCesta = new javax.swing.JMenuItem();
        jMenuItemListarCesta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBienvenido.setText("Bienvenido: ");

        jButtonLogOut.setText("Logout");
        jButtonLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogOutActionPerformed(evt);
            }
        });

        jMenu2.setText("Acciones");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });

        jMenuItemAlta.setText("Alta");
        jMenuItemAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemAlta);

        jMenuItemListar.setText("Listar");
        jMenuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarActionPerformed(evt);
            }
        });
        jMenuCliente.add(jMenuItemListar);

        jMenu2.add(jMenuCliente);

        jMenuProducto.setText("Producto");

        jMenuItemAltaProducto.setText("Alta Producto");
        jMenuItemAltaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltaProductoActionPerformed(evt);
            }
        });
        jMenuProducto.add(jMenuItemAltaProducto);

        jMenuItemListarProdcuto.setText("Listar Producto");
        jMenuItemListarProdcuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarProdcutoActionPerformed(evt);
            }
        });
        jMenuProducto.add(jMenuItemListarProdcuto);

        jMenu2.add(jMenuProducto);

        jMenuCesta.setText("Cesta");

        jMenuItemNuevaCesta.setText("Nueva");
        jMenuItemNuevaCesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNuevaCestaActionPerformed(evt);
            }
        });
        jMenuCesta.add(jMenuItemNuevaCesta);

        jMenuItemListarCesta.setText("Listar");
        jMenuItemListarCesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarCestaActionPerformed(evt);
            }
        });
        jMenuCesta.add(jMenuItemListarCesta);

        jMenu2.add(jMenuCesta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonLogOut)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelBienvenido)
                        .addGap(76, 76, 76)
                        .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBienvenido)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonLogOut)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogOutActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLogOutActionPerformed

    private void jMenuItemAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaActionPerformed
        GestionCliente gestion = new GestionCliente(null, AccionesEnum.ALTA);
        gestion.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItemAltaActionPerformed

    private void jMenuItemListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarActionPerformed
        ListarCliente listaClientes = new ListarCliente(null, true);
        listaClientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemListarActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed

    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuItemAltaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltaProductoActionPerformed
        GestionProducto gestion = new GestionProducto(null,AccionesEnum.ALTA);
        gestion.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemAltaProductoActionPerformed

    private void jMenuItemListarProdcutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarProdcutoActionPerformed
        ListarProducto listaProductos = new ListarProducto(null, true);
        listaProductos.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemListarProdcutoActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItemNuevaCestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNuevaCestaActionPerformed
        
        GestionCesta gestion = new GestionCesta();
        gestion.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jMenuItemNuevaCestaActionPerformed

    private void jMenuItemListarCestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarCestaActionPerformed
        ListarCesta listarCesta = new ListarCesta(usuario);
        listarCesta.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemListarCestaActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogOut;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCesta;
    private javax.swing.JMenu jMenuCliente;
    private javax.swing.JMenuItem jMenuItemAlta;
    private javax.swing.JMenuItem jMenuItemAltaProducto;
    private javax.swing.JMenuItem jMenuItemListar;
    private javax.swing.JMenuItem jMenuItemListarCesta;
    private javax.swing.JMenuItem jMenuItemListarProdcuto;
    private javax.swing.JMenuItem jMenuItemNuevaCesta;
    private javax.swing.JMenu jMenuProducto;
    // End of variables declaration//GEN-END:variables
}
