/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.CRUD_Usuario;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.Cliente;
import modelo.Usuario;
import utils.AccionesEnum;

/**
 *
 * @author Prueba
 */
public class GestionCliente extends javax.swing.JFrame {

    private AccionesEnum accion;
    private Cliente cliente;
    private CRUD_Usuario crudClientes = new CRUD_Usuario();
    private Usuario usuario;

    public GestionCliente(Usuario usuario, Cliente cliente, AccionesEnum accion) {
        this.usuario = usuario;
        this.cliente = cliente;
        this.accion = accion;
        initComponents();

        if (AccionesEnum.BAJA.equals(accion)) {
            mostrarDatosDeshabilitados(cliente);
        } else if (AccionesEnum.MODIFICACION.equals(accion)) {
            mostrarDatosHabilitados(cliente);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldDni = new javax.swing.JTextField();
        jLabelUSuario = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jButtonVolver = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente"));

        jLabelNombre.setText("Nombre: ");

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLabelApellidos.setText("Apellidos:");

        jLabel6.setText("DNI:");

        jTextFieldDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDniActionPerformed(evt);
            }
        });

        jLabelUSuario.setText("Dirección: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombre)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabelApellidos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldDni))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelUSuario)
                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(jTextFieldDireccion))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellidos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelUSuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(268, 268, 268))
        );

        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAceptar)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonVolver)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonVolver))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDniActionPerformed

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        if (AccionesEnum.ALTA.equals(accion)) {
            BienvenidoUsuario hola = new BienvenidoUsuario(usuario);
            dispose();
            hola.setVisible(true);
        } else {
            ListarCliente listarCliente = new ListarCliente(usuario, this, true);
            dispose();
            listarCliente.setVisible(true);

        }
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        // validamos que no haya una cuenta con el mismo numero ya existente

        // si no hay ninguna cuenta con el mismo número la damos de alta
        if (AccionesEnum.ALTA.equals(accion)) {
            Cliente cliente = recogerDatos();

            String dni = jTextFieldDni.getText();
            List<Usuario> misClientes = crudClientes.search(new Cliente(null, dni, null, null, null));
            if (misClientes.isEmpty()) {
                if (cliente != null && crudClientes.add(cliente)) {
                    JOptionPane.showMessageDialog(this, "Operación realizada correctamente.");
                    BienvenidoUsuario hola = new BienvenidoUsuario(usuario);
                    dispose();
                    hola.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Se ha producido un error.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ya hay un cliente con el mismo dni.");
            }
        }
        if (AccionesEnum.BAJA.equals(accion)) {
            if (cliente != null && crudClientes.delete(cliente)) {
                JOptionPane.showMessageDialog(this, "Operación realizada correctamente.");
                ListarCliente listarCliente = new ListarCliente(usuario, this, true);
                dispose();
                listarCliente.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Se ha producido un error.");
            }

        }
        if (AccionesEnum.MODIFICACION.equals(accion)) {
            Cliente cliente = recogerDatos();
            if (cliente != null && crudClientes.update(cliente)) {
                JOptionPane.showMessageDialog(this, "Operación realizada correctamente.");
                ListarCliente listarCliente = new ListarCliente(usuario, this, true);
                dispose();
                listarCliente.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Se ha producido un error.");
            }
        }

    }//GEN-LAST:event_jButtonAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelUSuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldDni;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    private Cliente recogerDatos() {
        Cliente cliente = null;
        boolean correcto = true;
        String errores = "";
        
        String nombre = jTextFieldNombre.getText();
        if(nombre.isEmpty()){
             errores = errores + "- El campo nombre es obligatorio.\n";
             correcto = false;
        }
               
        String apellidos = jTextFieldApellidos.getText();
        if(apellidos.isEmpty()){
             errores = errores + "- El campo apellidos es obligatorio.\n";
             correcto = false;
        }
        String direccion = jTextFieldDireccion.getText();
        if(direccion.isEmpty()){
             errores = errores + "- El campo dirección es obligatorio.\n";
             correcto = false;
        }
        String dni = jTextFieldDni.getText();
        if(dni.isEmpty()){
             errores = errores + "- El campo dni es obligatorio.\n";
             correcto = false;
        }
        
        if(correcto == true){
            cliente = new Cliente(false, dni, nombre, apellidos, direccion);
        }else{
            JOptionPane.showMessageDialog(this, errores);
        }

       

        return cliente;
    }

    private void mostrarDatosHabilitados(Cliente cliente) {

        jTextFieldNombre.setText(cliente.getNombre());
        jTextFieldApellidos.setText(cliente.getApellidos());
        jTextFieldDireccion.setText(cliente.getDireccion());
        jTextFieldDni.setText(cliente.getDni());
        // DNI lo tenemos establecido como primary key así que se tiene que mostrar deshabilitado
        jTextFieldDni.setEnabled(false);

    }

    private void mostrarDatosDeshabilitados(Cliente cliente) {

        jTextFieldNombre.setText(cliente.getNombre());
        jTextFieldNombre.setEnabled(false);
        jTextFieldApellidos.setText(cliente.getApellidos());
        jTextFieldApellidos.setEnabled(false);
        jTextFieldDireccion.setText(cliente.getDireccion());
        jTextFieldDireccion.setEnabled(false);
        jTextFieldDni.setText(cliente.getDni());
        jTextFieldDni.setEnabled(false);

    }

}
