/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import componentes.ComboItemProductos;
import componentes.TablaProductosCesta;
import controlador.CRUD_Cesta;
import controlador.CRUD_Productos;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import modelo.Cesta;
import modelo.Cliente;
import modelo.Producto;
import modelo.Usuario;
import utils.AccionesEnum;

public class GestionCesta extends javax.swing.JFrame {

    private Cliente cliente;
    private List<Producto> lista;
    private Cesta cesta;
    private TablaProductosCesta modeloTabla;
    private CRUD_Cesta crudCesta = new CRUD_Cesta();
    private CRUD_Productos crudProductos = new CRUD_Productos();
    private Producto producto;
    private Usuario usuario;
    private AccionesEnum accion;

    public GestionCesta(Usuario usuario, AccionesEnum accion) {
        this.usuario = usuario;
        this.accion = accion;
        this.lista = new ArrayList<>();
        initComponents();
        cargarComboProducto();
        jTextFieldTotal.setText(String.valueOf(0));
        inicializarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxProductos = new javax.swing.JComboBox();
        jButtonAgregar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonConfirmar.setText("Confirmar");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Total: ");

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Producto: ");

        jLabel3.setText("Nombre: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(jButtonEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConfirmar)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(124, 124, 124)
                                    .addComponent(jButtonAgregar))
                                .addComponent(jLabelNombre))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmar)
                    .addComponent(jButtonEliminar))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        ComboItemProductos productoSeleccionado = (ComboItemProductos) jComboBoxProductos.getSelectedItem();

        lista.add(productoSeleccionado.getProducto());
        inicializarTabla();

        Float total = Float.parseFloat(jTextFieldTotal.getText());

        total = total + productoSeleccionado.getProducto().getPrecio();

        jTextFieldTotal.setText(String.valueOf(total));

    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        Cesta cesta = recogerDatos();
        Boolean hayStock = true;

        Map<String, List<Producto>> productoMap = lista.stream().collect(Collectors.groupingBy(Producto::getId));
        for (Map.Entry<String, List<Producto>> entry : productoMap.entrySet()) {
            String idString = entry.getKey();
            List<Producto> cantidadStock = entry.getValue();

            Integer cantidadRestar = cantidadStock.size();

            Producto productoEncontrado = crudProductos.searchById(new Producto(idString, null, null, null));

            Integer nuevoStock = productoEncontrado.getStock() - cantidadRestar;
            if (nuevoStock <= 0) {
                JOptionPane.showMessageDialog(this, "No hay stock del producto " + producto.getNombre() + ".");
                hayStock = false;
            } else {
                productoEncontrado.setStock(nuevoStock);

                crudProductos.update(productoEncontrado);
            }

        }

        if (hayStock) {
            String id = cesta.getId();
            Cesta misCesta = crudCesta.searchById(new Cesta(id, null, null, null, null));
            if (misCesta == null) {
                if (cesta != null && crudCesta.add(cesta)) {
                    JOptionPane.showMessageDialog(this, "Operación realizada correctamente.");
                    BienvenidoUsuario hola = new BienvenidoUsuario(usuario);
                    dispose();
                    hola.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Se ha producido un error.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Ya hay un cesta con el mismo id.");
            }

        }


    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        lista.remove(producto);
        Float total = Float.parseFloat(jTextFieldTotal.getText());

        total = total - producto.getPrecio();

        jTextFieldTotal.setText(String.valueOf(total));
        inicializarTabla();
    }//GEN-LAST:event_jButtonEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JComboBox jComboBoxProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables

    private void inicializarTabla() {
        modeloTabla = new TablaProductosCesta(lista);
        this.jTable1.setModel(modeloTabla);
        jTable1.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 1) {
                    int filaSeleccionada = jTable1.getSelectedRow();
                    if (filaSeleccionada != -1) {
                        producto = lista.get(filaSeleccionada);
                    }
                }
            }

        });
    }

    private void cargarComboProducto() {
        crudProductos.getProductos().stream().forEach(producto -> this.jComboBoxProductos.addItem(new ComboItemProductos(producto)));
    }

    private Cesta recogerDatos() {
        Cesta cesta = null;
        boolean correcto = true;
        String errores = "";

        String nombre = jTextFieldNombre.getText();
        if (nombre.isEmpty()) {
            errores = errores + "- El campo nombre es obligatorio.\n";
            correcto = false;
        }

        Float total = Float.parseFloat(jTextFieldTotal.getText());
        if (correcto == true) {
            cesta = new Cesta(UUID.randomUUID().toString(), nombre, (Cliente) usuario, null, total);
        } else {
            JOptionPane.showMessageDialog(this, errores);
        }

        return cesta;

    }

}
